export const LOADING_PRODUCTS_BEGIN = "LOADING_PRODUCTS_BEGIN";
export const LOADING_PRODUCTS_END = "LOADING_PRODUCTS_END";
export const IS_LOADING_PRODUCTS_ERROR = "IS_LOADING_PRODUCTS_ERROR";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";
export const LOADING_SINGLE_PRODUCT_BEGIN = "LOADING_SINGLE_PRODUCT_BEGIN";
export const LOADING_SINGLE_PRODUCT_END = "LOADING_SINGLE_PRODUCT_END";
export const IS_LOADING_SINGLE_PRODUCT_ERROR =
  "IS_LOADING_SINGLE_PRODUCT_ERROR";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
